import React from "react";
import styles from "@/styles/Home.module.css";
import Head from "next/head";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

function Page({ children }) {
  return (
    <div className="main">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Sidebar />

        <div className={styles.grid}>
          <Header />
          {children}
        </div>
      </main>
    </div>
  );
}

export default Page;
